# -*- coding: utf-8 -*-
"""ML_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BGgliNek8bO16c6XRiopi9n1NJ1oOlR2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("/content/water_potability.csv")
df.head()
df.info()
df.describe()

df = df.fillna(df.mean())

X = df.drop("Potability", axis=1)
y = df["Potability"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

import matplotlib.pyplot as plt

df['Potability'].value_counts().plot(kind='bar')

plt.title("Safe vs Unsafe Water")
plt.xlabel("Potability (0 = Unsafe, 1 = Safe)")
plt.ylabel("Count")

plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()

plt.title("Confusion Matrix - Logistic Regression")
plt.show()

cm_dt = confusion_matrix(y_test, dt_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm_dt)
disp.plot()

plt.title("Confusion Matrix - Decision Tree")
plt.show()

cm_knn = confusion_matrix(y_test, knn_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm_knn)
disp.plot()

plt.title("Confusion Matrix - KNN")
plt.show()

from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

# store accuracies
lr_acc = accuracy_score(y_test, y_pred)
dt_acc = accuracy_score(y_test, dt_pred)
knn_acc = accuracy_score(y_test, knn_pred) # Now knn_pred should be defined

models = ['Logistic Regression', 'Decision Tree', 'KNN']
accuracies = [lr_acc, dt_acc, knn_acc]

plt.figure()
plt.bar(models, accuracies)

# show values on top
for i, v in enumerate(accuracies):
    plt.text(i, v, str(round(v, 2)), ha='center')

plt.title("Model Comparison")
plt.xlabel("Models")
plt.ylabel("Accuracy")

plt.show()

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("---- Logistic Regression ----")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

print("\n---- Decision Tree ----")
print("Accuracy:", accuracy_score(y_test, dt_pred))
print("Precision:", precision_score(y_test, dt_pred))
print("Recall:", recall_score(y_test, dt_pred))
print("F1 Score:", f1_score(y_test, dt_pred))

print("\n---- KNN ----")
print("Accuracy:", accuracy_score(y_test, knn_pred))
print("Precision:", precision_score(y_test, knn_pred))
print("Recall:", recall_score(y_test, knn_pred))
print("F1 Score:", f1_score(y_test, knn_pred))

sample = [[7.0, 180, 20000, 7.0, 300, 400, 10, 80, 4]]

prediction = model.predict(sample)

if prediction[0] == 1:
    print("Safe Water")
else:
    print("Unsafe Water")

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))